# Generated by Django 2.0.5 on 2018-05-15 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PBD_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('neighborhood', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='CPF',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 15, 2, 12, 16, 202188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='CNPJ',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
    ]
