# Generated by Django 2.0.5 on 2018-05-15 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PBD_library', '0002_auto_20180514_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 15, 21, 50, 54, 786394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
    ]
