# Generated by Django 2.0.5 on 2018-05-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PBD_library', '0004_auto_20180515_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PBD_library.Address'),
        ),
    ]
