# Generated by Django 2.0.5 on 2018-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBD_library', '0006_auto_20180515_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='lent',
            field=models.BooleanField(default=False),
        ),
    ]
